<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8" />
        <title>Personas</title>
    </head>
    <body>
        <table><tr><td><a href="index.php?controller=coches&action=view">Ver Coches <a/></td></tr></table> <br>
        <?php
            foreach ($datos as $dato) {
                echo "{$dato['nombre']} tiene {$dato['edad']} años." .
                     "<a href=\"index.php?controller=personas&action=delete&id={$dato['id']}\">Borrar</a><br/>";
            }
        ?>
        <br>
        <a href="index.php?controller=personas&action=add">Alta de Personas</a>
    </body>
</html>
